name: Deploy

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Create env file
        run: |
          touch .env
          echo "${{ secret.ENV_FILE }}" > .env

      - name: Build and run
        run: docker-compose up --build