name: Deploy

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - shell: bash
      env:
         FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
         PEPPER: ${{ secrets.PEPPER }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build and run
        run: docker-compose up --build