name: Deploy

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      env:
        FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
        PEPPER: ${{ secrets.PEPPER }}

    - name: Checkout code
      uses: actions/checkout@v6

    - name: Create env
      uses:

    - name: Build and run
      run: docker-compose up --build